/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id:"box4SFtGvA0",
    category:"Games",
    title:"Esports: Inside the relentless training of professional gaming stars",
    img: "http://img.youtube.com/vi/box4SFtGvA0/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=box4SFtGvA0&ab_channel=CBSNews",
    source:"CBS News ©",
},
{
    _id:"hNQC5GyumQ4",
    category:"Games",
    title:"The Story of Faker: The Greatest of All Time",
    img: "http://img.youtube.com/vi/hNQC5GyumQ4/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=hNQC5GyumQ4&ab_channel=theScoreesports",
    source:"theScore esports ©",
    videodetailState:{LikedVideos:false, AddPlayList:false, WatchLater:false},
},
{
    _id:"LEKpmHB4Xg8",
    category:"Games",
    title:"The Economics of Esports",
    img: "http://img.youtube.com/vi/LEKpmHB4Xg8/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=LEKpmHB4Xg8&ab_channel=JakeTran",
    source:"Jake Tran ©",
    videodetailState:{LikedVideos:false, AddPlayList:false, WatchLater:false},
},
{
    _id:"t8LD0iUYv80",
    category:"Sci_Fi",
    title:`Sci-Fi Short Film “FTL" | DUST`,
    img: "http://img.youtube.com/vi/t8LD0iUYv80/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=t8LD0iUYv80&ab_channel=DUST",
    source:"Dust ©",
    videodetailState:{LikedVideos:false, AddPlayList:false, WatchLater:false},
},
{
    _id:"P6EyjIvbex8",
    category:"Sci_Fi",
    title:"Top 20 Best Sci-Fi Movies of the Century (So Far)",
    img: "https://img.youtube.com/vi/P6EyjIvbex8/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=P6EyjIvbex8&ab_channel=WatchMojo.com",
    source:"WatchMojo.com ©",
},

{
    _id:"8aGhZQkoFbQ",
    category:"JavaScript",
    title:"What the heck is the event loop anyway? | Philip Roberts | JSConf EU",
    img: "http://img.youtube.com/vi/8aGhZQkoFbQ/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=8aGhZQkoFbQ&ab_channel=JSConf",
    source:"JSConf ©",
},
{
    _id:"Ezk2AwqgS9Q",
    category:"JavaScript",
    title:"launching neog.camp: roadmap to full stack dev",
    img: "http://img.youtube.com/vi/Ezk2AwqgS9Q/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=Ezk2AwqgS9Q&list=PLzvhQUIpvvuj5KPnyPyWsvgyzNkX_ACPA&ab_channel=TanayPratap",
    source:"Tanay Pratap ©",
},
{
    _id:"uD4izuDMUQA",
    category:"Documentary",
    title:"TIMELAPSE OF THE FUTURE: A Journey to the End of Time (4K)",
    img: "http://img.youtube.com/vi/uD4izuDMUQA/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=uD4izuDMUQA&ab_channel=melodysheep",
    source:"melodysheep ©",
},

{
    _id:"w9zmSAsGj1Q",
    category:"Saga",
    title:"Crusades From the Byzantine Perspective - Medieval History DOCUMENTARY",
    img: "http://img.youtube.com/vi/w9zmSAsGj1Q/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=w9zmSAsGj1Q&ab_channel=KingsandGenerals",
    source:"Kings and Generals ©",
},
{
    _id:"Gv4Af83KFrE",
    category:"Saga",
    title:"Forged in Fire: TOP 5 DEADLIEST WEAPONS FROM INDIA | History",
    img: "http://img.youtube.com/vi/Gv4Af83KFrE/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=Gv4Af83KFrE&ab_channel=HISTORY",
    source:"HISTORY ©",
},
{
    _id:"TZgyeEE2hx4",
    category:"Comedy",
    title:"MIDDLE CLASS RESTAURANT PROBLEMS : STAND UP COMEDY -Kenny Sebastian",
    img: "http://img.youtube.com/vi/TZgyeEE2hx4/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=TZgyeEE2hx4&ab_channel=KennySebastian",
    source:"Kenny Sebastian ©",
},
{
    _id:"5d8DpqthAGo",
    category:"Comedy",
    title:"PAKISTANIS ARE SAVAGE! Pt 5 feat. @Zakir Khan",
    img: "http://img.youtube.com/vi/5d8DpqthAGo/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=5d8DpqthAGo&ab_channel=TanmayBhat",
    source:"Tanmay Bhat ©",
},
{
    _id:"4IkTLiU5Q0k",
    category:"Comedy",
    title:"Shadows (A Stand-up Comedy Special by Daniel Fernandes)",
    img: "http://img.youtube.com/vi/4IkTLiU5Q0k/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=4IkTLiU5Q0k&ab_channel=DanielFernandes",
    source:"Daniel Fernandes ©",
},
{
    _id:"nH6WUTFmgg8",
    category:"Podcasts",
    title:"UNICORN Cred Founder Kunal Shah's Powerful Tips For Wealth & Success | The Ranveer...",
    img: "http://img.youtube.com/vi/nH6WUTFmgg8/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=nH6WUTFmgg8&ab_channel=BeerBiceps",
    source:"BeerBiceps ©",
},
{
    _id:"6x1i0K4Eg1g",
    category:"Podcasts",
    title:"12 Podcasts that Changed My Life",
    img: "http://img.youtube.com/vi/6x1i0K4Eg1g/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=6x1i0K4Eg1g&ab_channel=AliAbdaal",
    source:"Ali Abdaal ©",
},
{
    _id:"AQQNn7DH0VI",
    category:"Movies",
    title:"THE BEST UPCOMING MOVIES 2022 (Trailers)",
    img: "http://img.youtube.com/vi/AQQNn7DH0VI/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=AQQNn7DH0VI&ab_channel=KinoCheck.com",
    source:"KinoCheck.com ©",
},
{
    _id:"JKa05nyUmuQ",
    category:"Movies",
    title:"KGF Chapter 2 Trailer|Hindi|Yash|Sanjay Dutt|Raveena Tandon|Srinidhi...",
    img: "http://img.youtube.com/vi/JKa05nyUmuQ/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=JKa05nyUmuQ&ab_channel=ExcelMovies",
    source:"Excel Movies ©",
},
{
    _id:"YKSNBIlM_bY",
    category:"Movies",
    title:`Naruto: The Movie "Teaser Trailer" (2022) Live Action "Concept"`,
    img: "http://img.youtube.com/vi/YKSNBIlM_bY/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=YKSNBIlM_bY&ab_channel=FandomTopics",
    source:"Fandom Topics ©",
},
{
    _id:"Ua-b6CDFU-A",
    category:"Movies",
    title:"The Sea Beast | Official Teaser | Netflix",
    img: "http://img.youtube.com/vi/Ua-b6CDFU-A/maxresdefault.jpg",
    url: "https://www.youtube.com/watch?v=Ua-b6CDFU-A&ab_channel=Netflix",
    source:"Netflix ©",
},

];
